#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Ref-Util-XS
Version  : 0.117
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/X/XS/XSAWYERX/Ref-Util-XS-0.117.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/X/XS/XSAWYERX/Ref-Util-XS-0.117.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libr/libref-util-xs-perl/libref-util-xs-perl_0.117-1.debian.tar.xz
Summary  : 'XS implementation for Ref::Util'
Group    : Development/Tools
License  : MIT
Requires: perl-Ref-Util-XS-lib
Requires: perl-Ref-Util-XS-license
Requires: perl-Ref-Util-XS-man

%description
This archive contains the distribution Ref-Util-XS,
version 0.117:
XS implementation for Ref::Util

%package lib
Summary: lib components for the perl-Ref-Util-XS package.
Group: Libraries
Requires: perl-Ref-Util-XS-license

%description lib
lib components for the perl-Ref-Util-XS package.


%package license
Summary: license components for the perl-Ref-Util-XS package.
Group: Default

%description license
license components for the perl-Ref-Util-XS package.


%package man
Summary: man components for the perl-Ref-Util-XS package.
Group: Default

%description man
man components for the perl-Ref-Util-XS package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Ref-Util-XS-0.117
mkdir -p %{_topdir}/BUILD/Ref-Util-XS-0.117/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Ref-Util-XS-0.117/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Ref-Util-XS
cp LICENSE %{buildroot}/usr/share/doc/perl-Ref-Util-XS/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Ref/Util/XS.pm

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Ref/Util/XS/XS.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Ref-Util-XS/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Ref::Util::XS.3
